name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * 0" # Solo se ejecutará los domingos a medianoche
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: brandy-sinche-dev
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake
        uses: crazy-max/ghaction-github-pages@v3.1.0 # Usamos esta acción que es más limpia
        with:
          target_branch: output # Los archivos se van a una rama aparte
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
